<a href="https://colab.research.google.com/github/dbgml4647/Meachine-Learning-Study/blob/master/_0819_%EC%95%84%EC%9D%B4%EB%A6%AC%EC%8A%A4_%ED%92%88%EC%A2%85_%EC%98%88%EC%B8%A1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# 라이브러리 사용 
import tensorflow as tf
import pandas as pd

In [2]:
#과거의 데이터를 준비한다 
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)
아이리스.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [3]:
#원핫인코딩
인코딩 = pd.get_dummies(아이리스)
인코딩.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [4]:
print(인코딩.columns)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


In [6]:
#독립 변수, 종속 변수 

독립 = 인코딩[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 인코딩[['품종_setosa', '품종_versicolor',
       '품종_virginica']]
print(독립.shape, 종속.shape)       

(150, 4) (150, 3)


In [9]:
#모델의 구조를 만듭니다

X= tf.keras.layers.Input(shape=[4])
Y = tf.keras.layers.Dense(3,activation='softmax')(X)
model = tf.keras.models.Model(X,Y)
model.compile(loss='categorical_crossentropy',
              metrics='accuracy')

In [10]:
# 3.데이터로 모델을 학습(FIT)합니다.
model.fit(독립,종속,epochs=1000, verbose=0)
model.fit(독립,종속,epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1591 - accuracy: 0.9733
Epoch 2/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1583 - accuracy: 0.9733
Epoch 3/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1584 - accuracy: 0.9733
Epoch 4/10
5/5 [==============================] - 0s 1ms/step - loss: 0.1582 - accuracy: 0.9733
Epoch 5/10
5/5 [==============================] - 0s 1ms/step - loss: 0.1583 - accuracy: 0.9733
Epoch 6/10
5/5 [==============================] - 0s 3ms/step - loss: 0.1585 - accuracy: 0.9733
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1577 - accuracy: 0.9733
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1577 - accuracy: 0.9733
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1575 - accuracy: 0.9733
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1575 - accuracy: 0.9733


In [11]:
#모델을 이용하기

print(model.predict(독립[:5]))
print(종속[:5])

[[9.99009728e-01 9.90091707e-04 1.13062086e-07]
 [9.95517194e-01 4.48170304e-03 1.05999220e-06]
 [9.98211384e-01 1.78825099e-03 3.68556357e-07]
 [9.95171487e-01 4.82692337e-03 1.48389586e-06]
 [9.99257982e-01 7.41863041e-04 8.31337701e-08]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


In [12]:
print(model.predict(독립[-5:]))
print(종속[:5])

[[1.03460332e-06 7.89493471e-02 9.21049654e-01]
 [2.06574919e-06 1.79356754e-01 8.20641160e-01]
 [4.33735204e-06 1.97209090e-01 8.02786529e-01]
 [1.33992842e-06 6.46606386e-02 9.35338020e-01]
 [1.10491455e-05 2.64144808e-01 7.35844135e-01]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


In [13]:
print(model.predict(독립[-5:]))
print(종속[-5:])

[[1.03460332e-06 7.89493471e-02 9.21049654e-01]
 [2.06574919e-06 1.79356754e-01 8.20641160e-01]
 [4.33735204e-06 1.97209090e-01 8.02786529e-01]
 [1.33992842e-06 6.46606386e-02 9.35338020e-01]
 [1.10491455e-05 2.64144808e-01 7.35844135e-01]]
     품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1


In [14]:
#학습한 가중치 출력하기 
model.get_weights()

[array([[ 0.35755605,  0.25890496, -0.6466056 ],
        [ 3.2013335 ,  0.2138688 , -0.8801663 ],
        [-3.1854975 ,  0.25154525,  1.2510793 ],
        [-3.4360483 , -1.644328  ,  2.4689546 ]], dtype=float32),
 array([ 2.1901333,  1.0624535, -1.7899401], dtype=float32)]