<a href="https://colab.research.google.com/github/dbgml4647/Meachine-Learning-Study/blob/master/_0819_%EC%95%84%EC%9D%B4%EB%A6%AC%EC%8A%A4_%ED%92%88%EC%A2%85_%2B_%ED%9E%88%EB%93%A0%EB%A0%88%EC%9D%B4%EC%96%B4_%EC%98%88%EC%B8%A1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# 라이브러리 사용 
import tensorflow as tf
import pandas as pd

In [2]:
#과거의 데이터를 준비한다 
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)
아이리스.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [3]:
#원핫인코딩
인코딩 = pd.get_dummies(아이리스)
인코딩.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [4]:
print(인코딩.columns)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


In [6]:
#독립 변수, 종속 변수 

독립 = 인코딩[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 인코딩[['품종_setosa', '품종_versicolor',
       '품종_virginica']]
print(독립.shape, 종속.shape)       

(150, 4) (150, 3)


In [15]:
#모델의 구조를 만듭니다

X= tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation='swish')(X)
H = tf.keras.layers.Dense(8, activation='swish')(H)
H = tf.keras.layers.Dense(8, activation='swish')(H)
Y = tf.keras.layers.Dense(3,activation='softmax')(H)
model = tf.keras.models.Model(X,Y)
model.compile(loss='categorical_crossentropy',
              metrics='accuracy')

In [20]:
model.summary()

Model: "functional_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 4)]               0         
_________________________________________________________________
dense_1 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_3 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_4 (Dense)              (None, 3)                 27        
Total params: 211
Trainable params: 211
Non-trainable params: 0
_________________________________________________________________


In [16]:
# 3.데이터로 모델을 학습(FIT)합니다.
model.fit(독립,종속,epochs=1000, verbose=0)
model.fit(독립,종속,epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0465 - accuracy: 0.9867
Epoch 2/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0442 - accuracy: 0.9800
Epoch 3/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0424 - accuracy: 0.9867
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0578 - accuracy: 0.9800
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0492 - accuracy: 0.9867
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0474 - accuracy: 0.9867
Epoch 7/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0515 - accuracy: 0.9867
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0473 - accuracy: 0.9800
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0432 - accuracy: 0.9800
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0563 - accuracy: 0.9733


In [11]:
#모델을 이용하기

print(model.predict(독립[:5]))
print(종속[:5])

[[9.99009728e-01 9.90091707e-04 1.13062086e-07]
 [9.95517194e-01 4.48170304e-03 1.05999220e-06]
 [9.98211384e-01 1.78825099e-03 3.68556357e-07]
 [9.95171487e-01 4.82692337e-03 1.48389586e-06]
 [9.99257982e-01 7.41863041e-04 8.31337701e-08]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


In [17]:
print(model.predict(독립[-5:]))
print(종속[:5])

[[1.3604139e-27 1.9610039e-04 9.9980396e-01]
 [1.7850412e-23 4.8171394e-03 9.9518281e-01]
 [5.7086456e-24 7.7509005e-03 9.9224913e-01]
 [2.2244081e-27 2.6191448e-04 9.9973804e-01]
 [6.7707363e-21 9.7322807e-02 9.0267718e-01]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


In [18]:
print(model.predict(독립[-5:]))
print(종속[-5:])

[[1.3604139e-27 1.9610039e-04 9.9980396e-01]
 [1.7850412e-23 4.8171394e-03 9.9518281e-01]
 [5.7086456e-24 7.7509005e-03 9.9224913e-01]
 [2.2244081e-27 2.6191448e-04 9.9973804e-01]
 [6.7707363e-21 9.7322807e-02 9.0267718e-01]]
     품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1


In [19]:
#학습한 가중치 출력하기 
model.get_weights()

[array([[ 0.10116876,  0.56502616,  0.5036629 , -0.45014343,  0.24350776,
         -0.12009734,  0.01747745, -0.17828456],
        [-0.24247889,  0.7076198 ,  0.46678624,  0.43481964, -0.05711007,
         -0.06401046,  0.35817897,  0.6059837 ],
        [-0.34514797,  0.10254807,  0.8240076 , -0.2123067 ,  0.62809575,
         -0.22165547, -0.62610066, -0.46687123],
        [-0.73087525, -0.7191136 ,  0.02973144, -0.9631314 ,  0.8827381 ,
         -0.503802  , -0.41261744, -0.82469624]], dtype=float32),
 array([ 0.43655533,  0.3363426 , -0.03995506,  0.12120058, -0.22004801,
         0.45181543,  0.16312791,  0.275905  ], dtype=float32),
 array([[ 0.8945987 , -1.0012319 , -0.54767835,  0.35473523,  0.4030992 ,
          0.764314  , -1.0659106 , -0.6367366 ],
        [ 0.69165957,  0.2563143 ,  0.3897586 , -0.41102135, -0.45233077,
         -0.5702793 ,  0.50609535,  0.6381573 ],
        [ 0.7870301 ,  0.18601555,  0.4234857 ,  0.31867003, -0.38963905,
          0.58238983, -0.33301327,